services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # entrypoint:
    # - sleep
    # - infinity
    init: true
    volumes:
      # - extensions:/root/.vscode-server/extensions
      # - workspace:/workspace
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    user: vscode

# volumes:
#   extensions:
#   workspace: